### ISSUE TITLE
Resources for the Licenses episode 

### ISSUE THREAD

**Issue by orchid00** [LibraryCarpentry/lc-fair-research#13]
Here are some resources that are reusable that will complement the licenses episode. 
To be added here: https://github.com/LibraryCarpentry/lc-fair-research/blob/gh-pages/_episodes/06-licenses.md

* 4 Simple recommendations for Open Source Software https://softdev4research.github.io/4OSS-lesson/
  * Use a license: https://softdev4research.github.io/4OSS-lesson/03-use-license/index.html
* Top 10 FAIR Imaging https://librarycarpentry.org/Top-10-FAIR//2019/06/27/imaging/
  * Licensing your work: https://librarycarpentry.org/Top-10-FAIR//2019/06/27/imaging/#9-licensing-your-work
* The Turing Way a Guide for reproducible Research: https://the-turing-way.netlify.app/welcome
  * Licensing https://the-turing-way.netlify.app/reproducible-research/licensing.html
* The Open Science Training Handbook: https://open-science-training-handbook.gitbook.io/book/
  * Open Licensing and file formats https://open-science-training-handbook.gitbook.io/book/open-science-basics/open-licensing-and-file-formats#6-open-licensing-and-file-formats
* DCC How to license research data https://www.dcc.ac.uk/guidance/how-guides/license-research-data

**Comment by nehamoopen** [comment]
- Choose an open source license: https://choosealicense.com/

This is a nice resource that helps you select a license based on your needs and requirements, while also providing a clear overview of the license.

**Comment by libcce** [comment]
Added these resources https://github.com/LibraryCarpentry/lc-fair-research/pull/46

Thanks @nehamoopen @orchid00!

Note: The links are there but of course the license section needs to be updated.
