### ISSUE TITLE
Populate learning objectives for Episode 2 - Findable

### ISSUE THREAD

**Issue by kmhettne** [LibraryCarpentry/lc-fair-research#16]
Learning objectives are the highest level and focus on what the learner will learn.

**Comment by kmhettne** [comment]
I've submitted a pull request for this issue, but forgot to reference the issue... Will see if I can still do that, otherwise now you know!

**Comment by linajandren** [comment]
I think the suggested changes are good. We do need to consider how well the lesson material corresponds to the objectives.

**Comment by kmhettne** [comment]
Yes, indeed. I have approved the pulled request so you can see the changes in the actual episode now, but we can continue the discussion of course. At the end of the sprint we should probably clean up the issues and see which ones that can be closed.

**Comment by kmhettne** [comment]
I'm closing this issue now. If further refinement is need we can open a new issue stating that refinement is needed.
