### ISSUE TITLE
Populate learning objectives for Episode 4 - Interoperable

### ISSUE THREAD

**Issue by kmhettne** [LibraryCarpentry/lc-fair-research#18]
Learning objectives are the highest level and focus on what the learner will learn.

**Comment by bencomp** [comment]
We just had a short discussion in the Zoom call that the current objectives for Interoperable are more *lesson objectives* than *learner/learning objectives*, summarised in https://github.com/LibraryCarpentry/lc-fair-research/issues/9#issuecomment-681740713 by @linajandren.

**Comment by bencomp** [comment]
I think it makes sense to somehow link the objectives, questions and points to the guidelines for interoperable.

> I1. (meta)data use a formal, accessible, shared, and broadly applicable language for knowledge representation
> I2. (meta)data use vocabularies that follow FAIR principles
> I3. (meta)data include qualified references to other (meta)data

The current objectives are:
- Demystify the term 'interoperable'
- Identify widely used metadata standards for research, including generic and discipline-focussed examples
- Explain the role of controlled vocabularies in enabling FAIR data
- Discuss machine readability aspects of FAIR data
- Understand how linked data standards and conventions for metadata schema documentation relate to interoperability
- Explore controlled vocabulary tools.

How about: the learner should be able to…
- explain what makes data and software (more) interoperable
- Identify widely used metadata standards for research, including generic and discipline-focussed examples
- Explain the role of controlled vocabularies in enabling FAIR data
- Discuss machine readability aspects of FAIR data
- Understand how linked data standards and conventions for metadata schema documentation relate to interoperability

It's not as big a change as I thought it should be. I'm very open to suggestions.

**Comment by jezcope** [comment]
@bencomp I like the proposed changes, they make sense to me!

**Comment by linajandren** [comment]
I agree with your changes, but I'd like to think a little bit more on one of the objectives you left unchanged, namely "Discuss machine readability aspects of FAIR data" - this is fairly high level compared to some of the other objectives. Can we make it a little more digestible?

**Comment by pitviper6** [comment]
Hey there! I'm just jumping in. I'd like to start tackling the "Explain the role of controlled vocabularies in enabling FAIR data"  bit. Should I make that a separate issue and assign it to myself? or just note that here. I don't have a huge amount of time today, but I could at least get it started.

**Comment by pitviper6** [comment]
OH, never mind..this still seems to be in progress.

**Comment by kmhettne** [comment]
Going along with what @bencomp  and @linajandren suggested I would actually skip "discuss machine-readability aspects of FAIR data" because it is too high-level, and include "for machines" in the first objective instead. I would also suggest to focus on the actual Interoperability aspect here so not to say "enabling FAIR data" but "enabling interoperability".

- Explain what makes data and software (more) interoperable for machines
- Identify widely used metadata standards for for research, including generic and discipline-focussed examples
- Explain the role of controlled vocabularies for encoding data and for annotating metadata in enabling interoperability
- Understand how linked data standards and conventions for metadata schema documentation relate to interoperability

**Comment by bencomp** [comment]
@linajandren agreed, that objective is not really 'learnable'. I'm signing off for today, but it should be addressed. I think it relates/translates/comes down to

- understand that FAIR is about both humans and machines understanding data
- choose a data format or knowledge representation language that allows machine to understand the data, over other ways to represent knowledge that only humans can understand – but that is way too long and vague.

@pitviper6 the episode is still messy and indeed we're still discussing the learning objectives, so it suppose it's better to discuss what you want in Slack (or here) :)

**Comment by ragamouf** [comment]
This discussion is really helpful - thanks everyone!
@kmhettne I absolutely agree with your rephrasing of the learner objectives - def submit a pull request on that.

> Explain what makes data and software (more) interoperable for machines
> Identify widely used metadata standards for for research, including generic and discipline-focussed examples
> Explain the role of controlled vocabularies for encoding data and for annotating metadata in enabling interoperability
> Understand how linked data standards and conventions for metadata schema documentation relate to interoperability

@bencomp thanks for the focus on learner objectives. I think your last bullet points can be usefully transformed into key points at the end of the lesson:
> understand that FAIR is about both humans and machines understanding data
> choose a data format or knowledge representation language that allows machine to understand the data, over other ways to represent knowledge that only humans can understand – but that is way too long and vague.

For your second point, how about "Interoperability means choosing a data format or knowledge representation language that helps machines to understand the data"

**Comment by kmhettne** [comment]
Ok, sorry guys, I just committed the changes without creating a pull request! Gha, sometimes I still get a bit confused using git!

**Comment by kmhettne** [comment]
I have closed this issue and if we need to refine the objectives we can always open a new one.
