### ISSUE TITLE
Populate learning objectives for Episode 5 - Reusable

### ISSUE THREAD

**Issue by kmhettne** [LibraryCarpentry/lc-fair-research#19]
Learning objectives are the highest level and focus on what the learner will learn.

**Comment by kmhettne** [comment]
I actually think that Episode 6 - licenses should be part of this episode instead since licenses are key to reusability (principle R1.1) and it would be good to stick to the FAIR acronym as much as possible for the lesson.

**Comment by kmhettne** [comment]
A suggestion for the learning objective for licenses would then be:

- Explain the most crucial differences between the most common data and software licenses

**Comment by kmhettne** [comment]
I've submitted a pull request to update the objectives. See #37

**Comment by selgebali** [comment]
Hi @kmhettne  is this dealt with now and can we close this issue? :)

**Comment by kmhettne** [comment]
Yes!
