### ISSUE TITLE
Populate learning objectives for Episode 6 - Licenses

### ISSUE THREAD

**Issue by kmhettne** [LibraryCarpentry/lc-fair-research#20]
Learning objectives are the highest level and focus on what the learner will learn.

**Comment by linajandren** [comment]
There is not much content in this episode yet, but I think someone said they were going to work on it during the sprint? I started to think about learning objectives for reusable but these would probably be better off here. Would appreciate input!

How about:
understand how proper licensing is essential for reusability.
and
know about some of the licenses commonly used for data and software. (maybe this should be explicit about which licenses and make sure that the episode introduces these?)

**Comment by kmhettne** [comment]
I think this Episode should be moved to be part of Episode 5 - Reusable. The objectives are good, I added one more in the reusable issue.

**Comment by jezcope** [comment]
Yes, that makes sense: it's clearly part of R.1. "(meta)data are released with a clear and accessible data usage licence".

**Comment by kmhettne** [comment]
I have submitted a pull request to remove this episode and submitted a pull request to incorporate the learning objectives formulated by @linajandren for the licenses into the reusable episode.
