### ISSUE TITLE
Change "Scientific lifecycle" to "research lifecycle"

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/lc-fair-research#24]
I wanted to open this up for discussion before anyone started work on it: the [Introduction episode](https://github.com/LibraryCarpentry/lc-fair-research/blob/gh-pages/_episodes/01-introduction.md) references the "research lifecycle" and then uses this illustration which instead calls it the "scientific lifecycle". Given the generally narrower usage of the word "science" in English (usually referring to only the natural sciences) than other European languages (where it is mostly a proper synonym for "research"), should we change "science" to "research" here? Or perhaps clarify our definition of "science"?

![Scientific lifecycle](https://raw.githubusercontent.com/LibraryCarpentry/lc-fair-research/gh-pages/fig/pepe_research_lifecycle.png)

**Comment by arockenberger** [comment]
I think this should be renamed to "research" - and kept throughout the lesson. Since the material is in English, it's best to follow conventions here and use the more inclusive research instead of science.
Q: can we modify the image? i.e. is it licensed CC-BY or another appropriate license?

**Comment by linajandren** [comment]
I agree, research is a better word even though science is a common (mis)translation at least where I am.

**Comment by jezcope** [comment]
I actually don't think we can use this image at all, since the [version of the paper on arXiv](https://arxiv.org/abs/0906.2549) only has the minimal arXiv "Non-exclusive distribution" license and the version of record at <https://doi.org/10.1002/asi.21263> is behind a paywall. But @libcce may know more as he added it: if written permission was obtained we should mention that.

**Comment by jezcope** [comment]
@arockenberger @linajandren Yes, that's my feeling too: we should pick one and make sure it's consistent across the whole lesson, and "research" makes more sense in this context.

**Comment by nehamoopen** [comment]
+1 to go with 'research' instead of 'scientific'.

**Comment by libcce** [comment]
It's a great idea to move to a new image and to use "research". I had permission from the author for the last image but looks like that is a non issue now.

**Comment by reblake** [comment]
+1 for research.  I actually use "Research Data Lifecycle" myself.   Because research lifecycle implies something much broader to me.

**Comment by ragamouf** [comment]
+1 for 'research' over scientific.

**Comment by libcce** [comment]
This issue is being addressed by https://github.com/LibraryCarpentry/lc-fair-research/issues/30. Thanks @selgebali!
