### ISSUE TITLE
Should software be integrated throughout the whole lesson?

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/lc-fair-research#29]
The FAIR principles were originally developed for research data: discussions as to how (or even if) they apply to software are still ongoing in the wider research community. Issue raised by @nehamoopen during a Zoom call.

Two suggestions were made:

1. Include sections for "Data" and "Software" in each episode
2. Focus the main episodes on "Data" and then have a final episode to discuss how the principles translate to "Software"

**Comment by selgebali** [comment]
IMHO, the second option.

**Comment by nehamoopen** [comment]
I just made a pull request with a new 'episode' that focuses on FAIR software. It's a clean slate for us to gather information/resources on the topic, and we can always integrate it with the original episodes with some copy-paste magic later on.

This discussion should still continue I think, especially as to what a lesson might need to cover and how.

**Comment by ragamouf** [comment]
I think it makes sense to gather content and activities together under a software episode. I would expect the goals of that episode to be guiding good practices when dealing with software and FAIR data - ie what kinds of software is going to help you create FAIR data and are there practices from collaborative and open source software communities that support FAIR data?

Also relevant to discussion in #10 that @bencomp raised for key questions added to the interoperable episode.

**Comment by libcce** [comment]
Thanks to @nehamoopen we created an episode and we can open issues/PRs for the episode for now https://librarycarpentry.org/lc-fair-research/08-software/index.html. Closing this issue.
