### ISSUE TITLE
Research Life cycle Headings & Key Points

### ISSUE THREAD

**Issue by selgebali** [LibraryCarpentry/lc-fair-research#30]
In light of the myriad of "Research Data Life cycle figures" available including https://www.dcc.ac.uk/guidance/curation-lifecycle-model 
I would like to create one specifically for this lesson and would, therefore, like to ask you to add what you think is should be included under the following themes:
1- Planning:
- Data management planning (DMPs) 
- Data description and metadata extraction
- Data documentation
- Choice of repositories
- Choices of file formats
- Data re-use
- Funders requirements
- File naming
- Ethics and Research conduct
- Funding for RDM activities

2- Managing:
- Storage and backup & security
- Active Metadata collection 
- Tools and software solutions
- Curation
- Versioning
- Provenance

3- Sharing
- Data access and Sharing rights
- Data privacy and GDPR compliance
- Data ownership, licensing 
- Data Transfer 
- GDPR

4- Preservation and Publication
- Citation
- PrePrint
- DOI
- Publishing requirements
- Long Term Storage 
- Archival and Disposal policies

Please feel free to edit/add as you see fit.

**Comment by reblake** [comment]
Provenance would be good to add under the Managing section.

**Comment by linajandren** [comment]
Something about long-term storage/preservation under number 4?
Also, maybe, a problem that seems to be common here is funding for data management -not always clear who is responsible, not always eligible for funding and not always considered when applying for money. Don’t know if this experience holds for others too? Could go into number 1 if others agree that it should be included.

**Comment by libcce** [comment]
@selgebali et al do you think this lifecycle image addresses what we discussed in the sprint https://blogs.helsinki.fi/thinkopen/know-your-data-rdm-series-1/ ? @ragamouf @kmhettne

**Comment by selgebali** [comment]
![Untitled presentation(1)](https://user-images.githubusercontent.com/23166543/93782320-babd1000-fc2a-11ea-940a-9438cc9892d0.jpg)

how about this one? It is not so fancy, but it includes all the points discussed above! If anyone else willing to take a crack at it, I'm also happy to send the original file :)

**Comment by selgebali** [comment]
<img width="874" alt="Screenshot 2020-09-26 at 14 33 01" src="https://user-images.githubusercontent.com/23166543/94343166-942a1b00-0016-11eb-8bb7-d70084eb5cf7.png">

This is the flipped version.

**Comment by kmhettne** [comment]
This looks really great! I was looking for the "Licensing" under Preservation and Publication, but I guess it is actually better under Sharing. I was also thinking that "Research Data Lifecycle" might be ore suitable since it is very focused on data? If you can make this small change I think we can close this issue.

**Comment by selgebali** [comment]
Thank you all for the feedback! @kmhettne now I updated the introduction and added Data, Thank you 🥇 !!!
I will close this issue now 👍
