### ISSUE TITLE
Ask contributors to use persistent identifiers (like DOIs) in lesson contents

### ISSUE THREAD

**Issue by bencomp** [LibraryCarpentry/lc-fair-research#43]
As a follow-up to #11, lesson contributors should be requested to use persistent identifiers (PIDs) to articles, datasets and other research objects.

I suppose (and suggested in https://github.com/LibraryCarpentry/lc-fair-research/pull/38#issue-475268419) that the pull request template has a message or checklist item reminding authors to use PIDs or that an automatic check is run on the contents.

**Comment by libcce** [comment]
I've added https://github.com/LibraryCarpentry/lc-fair-research/pull/45. Thanks @bencomp!
