### ISSUE TITLE
Typo in Top 10 FAIR Data and Software Things: Nanotechnology (checkout)

### ISSUE THREAD

**Issue by hnake** [LibraryCarpentry/lc-fair-research#77]
In the first sentence under "Description" on page https://librarycarpentry.org/Top-10-FAIR//2019/09/09/nanotechnology/, the word "interoperability" is currently misspelled as "interopera_bility" and should be fixed.

**Comment by libcce** [comment]
Thanks @hnake! See https://github.com/LibraryCarpentry/Top-10-FAIR/pull/33.
